
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALABASTER = 11;
  public static final int FUNCTION = 50;
  public static final int L_FATHERCHRISTMAS = 26;
  public static final int PINO = 2;
  public static final int SANNICOLAS = 23;
  public static final int FINREGALO = 46;
  public static final int HADA = 37;
  public static final int PERSONA = 48;
  public static final int KRISKRINGLE = 22;
  public static final int CIERRACUENTO = 31;
  public static final int DANCER = 4;
  public static final int DUENDE = 38;
  public static final int RUDOLPH = 8;
  public static final int ENTREGA = 47;
  public static final int CIERRAREGALO = 35;
  public static final int ABREEMPAQUE = 32;
  public static final int CIERRAEMPAQUE = 33;
  public static final int NARRA = 44;
  public static final int MAIN = 51;
  public static final int HACE = 40;
  public static final int ENVUELVE = 39;
  public static final int GRINCH = 9;
  public static final int EOF = 0;
  public static final int JINGLE = 16;
  public static final int CORTA = 43;
  public static final int SANTACLAUS = 20;
  public static final int MELCHOR = 17;
  public static final int REVISA = 41;
  public static final int error = 1;
  public static final int L_SANNICOLAS = 28;
  public static final int GASPAR = 18;
  public static final int ABRECUENTO = 30;
  public static final int PEPPER = 13;
  public static final int ESCUCHA = 45;
  public static final int PRANCER = 5;
  public static final int ABREREGALO = 34;
  public static final int DASHER = 3;
  public static final int L_KRISKRINGLE = 27;
  public static final int ENVIA = 42;
  public static final int DEDMOROZ = 24;
  public static final int BALTAZAR = 19;
  public static final int COMET = 7;
  public static final int BUSHY = 12;
  public static final int SUGARPLUM = 14;
  public static final int ELFO = 36;
  public static final int LOCAL = 49;
  public static final int WUNORSE = 15;
  public static final int FATHERCHRISTMAS = 21;
  public static final int VIXEN = 6;
  public static final int QUIEN = 10;
  public static final int L_SANTACLAUS = 25;
  public static final int L_DEDMOROZ = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PINO",
  "DASHER",
  "DANCER",
  "PRANCER",
  "VIXEN",
  "COMET",
  "RUDOLPH",
  "GRINCH",
  "QUIEN",
  "ALABASTER",
  "BUSHY",
  "PEPPER",
  "SUGARPLUM",
  "WUNORSE",
  "JINGLE",
  "MELCHOR",
  "GASPAR",
  "BALTAZAR",
  "SANTACLAUS",
  "FATHERCHRISTMAS",
  "KRISKRINGLE",
  "SANNICOLAS",
  "DEDMOROZ",
  "L_SANTACLAUS",
  "L_FATHERCHRISTMAS",
  "L_KRISKRINGLE",
  "L_SANNICOLAS",
  "L_DEDMOROZ",
  "ABRECUENTO",
  "CIERRACUENTO",
  "ABREEMPAQUE",
  "CIERRAEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "NARRA",
  "ESCUCHA",
  "FINREGALO",
  "ENTREGA",
  "PERSONA",
  "LOCAL",
  "FUNCTION",
  "MAIN"
  };
}

